const categoryList = [
  {id: '1', name: 'IT', img: require('../../assets/category/1.png')},
  {id: '2', name: '뉴스', img: require('../../assets/category/2.png')},
  {id: '3', name: '트렌드', img: require('../../assets/category/3.png')},
  {id: '4', name: '일상･에세이', img: require('../../assets/category/4.png')},
  {id: '5', name: '음악', img: require('../../assets/category/5.png')},
  {id: '6', name: '뷰티', img: require('../../assets/category/6.png')},
  {id: '7', name: '라이프스타일', img: require('../../assets/category/7.png')},
  {id: '8', name: '패션', img: require('../../assets/category/8.png')},
  {id: '9', name: '여행･아웃도어', img: require('../../assets/category/9.png')},
  {id: '10', name: '자기계발', img: require('../../assets/category/10.png')},
  {id: '11', name: '정치', img: require('../../assets/category/11.png')},
  {id: '12', name: '스포츠', img: require('../../assets/category/12.png')},
  {id: '13', name: '철학', img: require('../../assets/category/13.png')},
  {id: '14', name: '역사', img: require('../../assets/category/14.png')},
  {id: '15', name: '푸드', img: require('../../assets/category/15.png')},
  {id: '16', name: '디자인', img: require('../../assets/category/16.png')},
  {id: '17', name: '금융', img: require('../../assets/category/17.png')},
  {id: '18', name: '경제', img: require('../../assets/category/18.png')},
  {id: '19', name: '그림･예술', img: require('../../assets/category/19.png')},
  {id: '20', name: '부동산', img: require('../../assets/category/20.png')},
  {id: '21', name: '비즈니스', img: require('../../assets/category/21.png')},
  {id: '22', name: '펫･동물', img: require('../../assets/category/22.png')},
  {
    id: '23',
    name: '인테리어･리빙',
    img: require('../../assets/category/23.png'),
  },
];

export default categoryList;
