const categoryList = [
  {id: '1', name: 'IT', img: require('../../assets/category/1.jpg')},
  {id: '2', name: '뉴스', img: require('../../assets/category/2.jpg')},
  {id: '3', name: '트렌드', img: require('../../assets/category/3.jpg')},
  {id: '4', name: '일상･에세이', img: require('../../assets/category/4.jpg')},
  {id: '5', name: '음악', img: require('../../assets/category/5.jpg')},
  {id: '6', name: '뷰티', img: require('../../assets/category/6.jpg')},
  {id: '7', name: '라이프스타일', img: require('../../assets/category/7.jpg')},
  {id: '8', name: '패션', img: require('../../assets/category/8.jpg')},
  {id: '9', name: '여행･아웃도어', img: require('../../assets/category/9.jpg')},
  {id: '10', name: '자기계발', img: require('../../assets/category/10.jpg')},
  {id: '11', name: '정치', img: require('../../assets/category/11.jpg')},
  {id: '12', name: '스포츠', img: require('../../assets/category/12.jpg')},
  {id: '13', name: '철학', img: require('../../assets/category/13.jpg')},
  {id: '14', name: '역사', img: require('../../assets/category/14.jpg')},
  {id: '15', name: '푸드', img: require('../../assets/category/15.jpg')},
  {id: '16', name: '디자인', img: require('../../assets/category/16.jpg')},
  {id: '17', name: '금융', img: require('../../assets/category/17.jpg')},
  {id: '18', name: '경제', img: require('../../assets/category/18.jpg')},
  {id: '19', name: '그림･예술', img: require('../../assets/category/19.jpg')},
  {id: '20', name: '부동산', img: require('../../assets/category/20.jpg')},
  {id: '21', name: '비즈니스', img: require('../../assets/category/21.jpg')},
  {id: '22', name: '펫･동물', img: require('../../assets/category/22.jpg')},
  {
    id: '23',
    name: '인테리어･리빙',
    img: require('../../assets/category/23.jpg'),
  },
];

export default categoryList;
