const categoryList = [
  {id: '1', name: 'IT'},
  {id: '2', name: '뉴스'},
  {id: '3', name: '트렌드'},
  {id: '4', name: '일상･에세이'},
  {id: '5', name: '음악'},
  {id: '6', name: '뷰티'},
  {id: '7', name: '라이프스타일'},
  {id: '8', name: '패션'},
  {id: '9', name: '여행･아웃도어'},
  {id: '10', name: '자기계발'},
  {id: '11', name: '정치'},
  {id: '12', name: '스포츠'},
  {id: '13', name: '철학'},
  {id: '14', name: '역사'},
  {id: '15', name: '푸드'},
  {id: '16', name: '디자인'},
  {id: '17', name: '금융'},
  {id: '18', name: '경제'},
  {id: '19', name: '그림･예술'},
  {id: '20', name: '부동산'},
  {id: '21', name: '비즈니스'},
  {id: '22', name: '펫･동물'},
  {id: '23', name: '인테리어･리빙'},
];

export default categoryList;
